apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness
  labels:
    app: aceest-fitness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
  template:
    metadata:
      labels:
        app: aceest-fitness
    spec:
      containers:
      - name: aceest-fitness-container
        # Jenkins will replace this value with the built image tag
        image: RatnPriya03/aceest-fitness:LATEST_TAG_TO_BE_REPLACED
        ports:
        - containerPort: 5000
        # Pass the version as an environment variable to the app
        env:
        - name: APP_VERSION
          value: LATEST_TAG_TO_BE_REPLACED