apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  type: LoadBalancer # Uses Minikube's host access
  selector:
    app: aceest-fitness
  ports:
    - protocol: TCP
      port: 8081 # Service external port
      targetPort: 5000 # Container port
      